// <auto-generated />
using System;
using Ef.Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Ef.Test.Migrations
{
    [DbContext(typeof(EfTestContext))]
    [Migration("20210602085251_Table2NameField")]
    partial class Table2NameField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Ef.Test.Data.Table1", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long[]>("Table2Ids")
                        .HasColumnType("bigint[]")
                        .HasColumnName("table2_ids");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Table2Ids" }, "ix_table1_table2_ids")
                        .HasMethod("gin");

                    b.ToTable("table1");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Table2Ids = new[] { 1L }
                        },
                        new
                        {
                            Id = 2L,
                            Table2Ids = new[] { 1L, 2L }
                        },
                        new
                        {
                            Id = 3L
                        });
                });

            modelBuilder.Entity("Ef.Test.Data.Table2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("table2");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Name1"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Name2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
